### ISSUE TITLE
Fails to parse openjson I just downloaded from upverter

### ISSUE THREAD

**Issue by dcmcshan** [upverter/schematic-file-converter#195]
Seems your parser can't read files from your own website? 

$ python -m upconvert.upconverter -i d4c4da9cc37ec93f_14170229620293.upv -f openjson -o Master.sch -t eagle --unsupported
WARNING: RUNNING UNSUPPORTED VERSION OF PYTHON (2.7 > 2.6)
DEBUG:main:parsing d4c4da9cc37ec93f_14170229620293.upv in format openjson
DEBUG:parser.openjson:Starting parse of d4c4da9cc37ec93f_14170229620293.upv
ERROR: Failed to parse openjson

**Comment by rboyd** [comment]
+1

**Comment by elijahparker** [comment]
> $ python -m upconvert.upconverter -i e4ebe83c98a19c4f_14534014140000.upv -f openjson -o view -t eagle --unsupported
WARNING: RUNNING UNSUPPORTED VERSION OF PYTHON (2.7 > 2.6)
DEBUG:main:parsing e4ebe83c98a19c4f_14534014140000.upv in format openjson
DEBUG:parser.openjson:Starting parse of /Users/elijah/Downloads/e4ebe83c98a19c4f_14534014140000.upv
ERROR: Failed to parse openjson

Same here...did the openjson format change already?  Is there a new conversion utility in the works still, or was this abandoned?

**Comment by rcfox** [comment]
Hi guys,
Yes, this version of the schematic file converter is severely out of date, as stated in the readme.

Releasing an up-to-date version is planned, but a very low priority right now. Sorry!
